theme="kanabox"

[editor]
line-number="relative"
auto-completion=true
auto-format=true

[editor.lsp]
enable=true
auto-signature-help=true
display-inlay-hints=true
snippets=true
goto-reference-include-declaration=true

[editor.cursor-shape]
normal="block"
insert="bar"
select="underline"


